### ISSUE TITLE
Build error using llvm-15.0.0 (released version)

### ISSUE THREAD

**Issue by heitbaum** [mystor/synstructure#55]
Heads up on build error with llvm 15.

```
   Compiling synstructure v0.12.6
     Running `/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/bootstrap/debug/rustc --crate-name synstructure --edition=2018 /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/vendor/synstructure/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=0 -C debug-assertions=off --cfg 'feature="default"' --cfg 'feature="proc-macro"' -Zunstable-options --check-cfg 'values(feature, "default", "proc-macro")' --check-cfg 'names()' --check-cfg 'values()' -C metadata=071dd4eea66f2615 -C extra-filename=-071dd4eea66f2615 --out-dir /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps -C linker=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/host-gcc -L dependency=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps --extern proc_macro2=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps/libproc_macro2-ece12ca8e5b8c2f9.rmeta --extern quote=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps/libquote-5e49e8ee804b6b65.rmeta --extern syn=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps/libsyn-ef46fd2c975d6d4b.rmeta --extern unicode_xid=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps/libunicode_xid-5f0a0e7b23aae2ac.rmeta --cap-lints allow -Z binary-dep-depinfo`
The following warnings were emitted during compilation:

warning: llvm-wrapper/PassWrapper.cpp: In lambda function:
warning: llvm-wrapper/PassWrapper.cpp:988:43: error: 'ASanGlobalsMetadataAnalysis' was not declared in this scopewarning:   988 |           MPM.addPass(RequireAnalysisPass<ASanGlobalsMetadataAnalysis, Module>());
warning:       |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: llvm-wrapper/PassWrapper.cpp:988:78: error: template argument 1 is invalid
warning:   988 |           MPM.addPass(RequireAnalysisPass<ASanGlobalsMetadataAnalysis, Module>());
warning:       |                                                                              ^

error: failed to run custom build command for `rustc_llvm v0.0.0 (/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/compiler/rustc_llvm)`

Caused by:
  process didn't exit successfully: `/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/x86_64-unknown-linux-gnu/stage0-rustc/release/build/rustc_llvm-6145e3cf27ae77f4/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=RUST_CHECK
  cargo:rerun-if-env-changed=REAL_LIBRARY_PATH_VAR
  cargo:rerun-if-env-changed=REAL_LIBRARY_PATH
  cargo:rerun-if-env-changed=LLVM_CONFIG
  cargo:rerun-if-changed=/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/llvm-config
  cargo:rustc-cfg=llvm_component="amdgpu"
  cargo:rustc-cfg=llvm_component="asmparser"
  cargo:rustc-cfg=llvm_component="bitreader"
  cargo:rustc-cfg=llvm_component="bitwriter"
  cargo:rustc-cfg=llvm_component="coverage"
  cargo:rustc-cfg=llvm_component="instrumentation"
  cargo:rustc-cfg=llvm_component="ipo"
  cargo:rustc-cfg=llvm_component="linker"
  cargo:rustc-cfg=llvm_component="lto"
  cargo:rustc-cfg=llvm_component="x86"
  cargo:rerun-if-env-changed=LLVM_RUSTLLVM
  cargo:rerun-if-env-changed=LLVM_NDEBUG
  cargo:rerun-if-changed=llvm-wrapper/PassWrapper.cpp
  cargo:rerun-if-changed=llvm-wrapper/RustWrapper.cpp
  cargo:rerun-if-changed=llvm-wrapper/CoverageMappingWrapper.cpp
  cargo:rerun-if-changed=llvm-wrapper/ArchiveWrapper.cpp
  cargo:rerun-if-changed=llvm-wrapper/Linker.cpp
  cargo:rerun-if-changed=llvm-wrapper/README
  cargo:rerun-if-changed=llvm-wrapper/.editorconfig
  cargo:rerun-if-changed=llvm-wrapper/LLVMWrapper.h
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CXX_x86_64-unknown-linux-gnu = Some("/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/host-g++")
  CXXFLAGS_x86_64-unknown-linux-gnu = Some("-ffunction-sections -fdata-sections -fPIC -m64")
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,llvm14-builtins-abi,sse,sse2")
  running: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/host-g++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/include" "-std=c++14" "-fno-exceptions" "-fno-unwind-tables" "-fno-asynchronous-unwind-tables" "-D_GNU_SOURCE" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DLLVM_COMPONENT_AMDGPU" "-DLLVM_COMPONENT_ASMPARSER" "-DLLVM_COMPONENT_BITREADER" "-DLLVM_COMPONENT_BITWRITER" "-DLLVM_COMPONENT_COVERAGE" "-DLLVM_COMPONENT_INSTRUMENTATION" "-DLLVM_COMPONENT_IPO" "-DLLVM_COMPONENT_LINKER" "-DLLVM_COMPONENT_LTO" "-DLLVM_COMPONENT_X86" "-DNDEBUG" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-adc40500fff80c6d/out/llvm-wrapper/PassWrapper.o" "-c" "llvm-wrapper/PassWrapper.cpp"
  cargo:warning=llvm-wrapper/PassWrapper.cpp: In lambda function:
  cargo:warning=llvm-wrapper/PassWrapper.cpp:988:43: error: 'ASanGlobalsMetadataAnalysis' was not declared in this scope
  cargo:warning=  988 |           MPM.addPass(RequireAnalysisPass<ASanGlobalsMetadataAnalysis, Module>());
  cargo:warning=      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=llvm-wrapper/PassWrapper.cpp:988:78: error: template argument 1 is invalid
  cargo:warning=  988 |           MPM.addPass(RequireAnalysisPass<ASanGlobalsMetadataAnalysis, Module>());
  cargo:warning=      |                                                                              ^
  exit status: 1

  --- stderr


  error occurred: Command "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/bin/host-g++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/toolchain/include" "-std=c++14" "-fno-exceptions" "-fno-unwind-tables" "-fno-asynchronous-unwind-tables" "-D_GNU_SOURCE" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DLLVM_COMPONENT_AMDGPU" "-DLLVM_COMPONENT_ASMPARSER" "-DLLVM_COMPONENT_BITREADER" "-DLLVM_COMPONENT_BITWRITER" "-DLLVM_COMPONENT_COVERAGE" "-DLLVM_COMPONENT_INSTRUMENTATION" "-DLLVM_COMPONENT_IPO" "-DLLVM_COMPONENT_LINKER" "-DLLVM_COMPONENT_LTO" "-DLLVM_COMPONENT_X86" "-DNDEBUG" "-o" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-adc40500fff80c6d/out/llvm-wrapper/PassWrapper.o" "-c" "llvm-wrapper/PassWrapper.cpp" with args "host-g++" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
command did not execute successfully: "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/rust-snapshot/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-Zcheck-cfg=names,values,features" "-Zbinary-dep-depinfo" "-j" "8" "-v" "--release" "--frozen" "--features" "llvm max_level_info" "--manifest-path" "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/compiler/rustc/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit status: 101
Traceback (most recent call last):
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/src/bootstrap/bootstrap.py", line 1102, in <module>
    main()
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/src/bootstrap/bootstrap.py", line 1085, in main
    bootstrap(help_triggered)
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/src/bootstrap/bootstrap.py", line 1071, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/src/bootstrap/bootstrap.py", line 200, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/rust-1.63.0/build/bootstrap/debug/bootstrap -j 8 build --stage 2 --verbose
```

**Comment by heitbaum** [comment]
Build error still occurring with llvm-15.0.0 (released version)

**Comment by heitbaum** [comment]
See
- https://github.com/rust-lang/rust/pull/98621
- https://github.com/rust-lang/rust/pull/98632
